services:

    #
    # Factory
    #

    acilia.mailer.factory:
        class : Acilia\Bundle\MailerBundle\Service\MailerService
        tags :
            - { name: acilia.mailer.factory }

    acilia.mailer.member.factory:
        class : Acilia\Bundle\MailerBundle\Service\MemberService
        tags :
            - { name: acilia.mailer.member.factory }

    #
    # Providers
    #

    acilia.mailer.provider.smart_focus:
        class : Acilia\Bundle\MailerBundle\Library\Providers\SmartFocusProvider
        tags :
            - { name: acilia.mailer.provider }

    acilia.mailer.provider.swift_mailer:
        class : Acilia\Bundle\MailerBundle\Library\Providers\SwiftMailerProvider
        arguments: ["@mailer"]
        tags :
            - { name: acilia.mailer.provider }


    #
    # Members
    #

    acilia.mailer.member.smart_focus:
        class : Acilia\Bundle\MailerBundle\Library\Members\SmartFocusMember
        arguments: ["%acilia_mailer.smartfocus_member.server%"]
        tags :
            - { name: acilia.mailer.member }